const int d = 10
const int b = 20, a = 30

prot teste()

def soma(int a)
    a = 2
endp

def teste()
    do soma(d)
    const int z = 20
endp



def init 
   const int b = 2
   int c[d][a] = {1,2,3,4,5}
   int fat,n,z
   getint n
   if (n <= 1)
        fat = 1
    else
        fat = n 
        z = n
        while (z > a[2])
            z = z - 1
            fat = fat * z
            
        endw
    endi

    a = b[2] + 3
endp

